language: java
jdk:
- oraclejdk7
- openjdk7
- oraclejdk8
env:
  global:
  - FTP_USER="khazaddum.caltech.edu|warpdrive"
  - secure: rnP6qHsQDukvZt1BeWLcK4DetcqzfmP2cRUYlNYk6lpGpgiIRP0RE4MbHJGgR0HNG93pIRcxjH7hHXKY1tbLZT7CBQBZmpAB7pTBPP1udmv7hV43vuoq5G8jYNO9lPqbFnREnM9/1b+REWfkedREenrPpbMdnIGukrYPxKJeh9UPRNrExIuBdVYCiGgleST3YrBtrWadRqRLB7I7YjhhcnxAtMG8SSea1r0tFBdD+XMeST7XBX3WPrMEfUDICpFJyReCAIKdDwJj2tgjHrWH7+h2jp6KljmRuS69Ody6ClhJ6Lsj3d+3yVAV2aqQDCxkBYqJA5bSq0rdOg8jn0qY9OD3rJtxzaZchfwXsEovs1KK2vJDEzti0zJOVm2W9ZB/KGawvD+bOnAsioOq3L4+HFJ9HfaU6gds0MvozdjydyWBWk+P1RiCdYLBOzKo4Z/LiD4KHvw9colQuJ+41mijWt7p3DQ2ijB/NrfbuBhGkRp3d1vcxLTKhTh3Q2eyqnhYgVlLyGmCVFqIsW18mXlnh5b/EptIpV9oLv3bz1MFjZtbl4p9mOaxK+nkvDV4yXgigmFAH5se/gmpKfj7wXacIdvyiQZmsBOK1sUpQAlf/kOueuJd0WXnVInZqnrjj2/JHCbb43zVb9iHd9NgHL1HkhPwdd+FDWk1LLPJMf+1PNk=
before_install:
- chmod +x gradlew
before_deploy:
- echo "deploying ${RELEASE_FILE} to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: IzGBMb7m6y5DgoeNtlcRU4vnfnpULwrLEqbYnrK65mXh8LFR5QXRPcS5qhMctwbl4ZCXxe8BMSUegFo3grRPDQ8m1CJDt6Jh6+GydhQbuf5NtUOFMTrH5s2Ob5q23xXhxJGrQEFCm+a0L9YPDAV234UTOdUZZ6KAow5+E8hVx3PZGFWgFMUmSa/uX0Aqh++FfRMDcWtRtp9r6sth23JCgcO4Ryxohd67OYvFbvhoHBLDG5SpD0iRweY/uLVA/DIZuazdb+grqGocjCpzrh8a/bbUxUF4CbJOiInY2/9EuSgIIC267K5P76UKEAutMtC2/vx/EdHNapTRGjgXCU8FOBkepFZ6Rc97mPxFDvCK0xBIRcftO4f1fs27SS/MkQBaEVqd8wZxuDDcHcX3H2+84VM+9isGBmNdxgz+r5RDnDKcfATg3c2saN4X6Lz/CP4kVjiGb02rwZlS2e8BZIFWi/ahdEJY/IdzfnbfS5S+7hxddbtIOWnNsZ2JLTN0MzJYCCD6IXTloUBmljokQgB1vRY4Xzm7iDeF/yew2Jiuo1JoQI9RVlbBOXY+XobCz93yjeFvhOHIm/1y5wZff5bFO9LAshEwCriD1wjcnpac4qvy/RpRzUKnvUZyGoWdNBq8egrY3EZT7rV0DRFeiXLG6j1BB65LjvlK0wWhadn6Kps=
  file_glob: true
  file: "${RELEASE_FILE}"
  on:
    repo: LemADEC/WarpDrive
    branch: MC1.7
    tags: true
    jdk: oraclejdk7
after_success:
- export RELEASE_FILE=$(ls build/libs/*.jar)
- curl --ftp-ssl -3 -k --ftp-create-dirs -T ${RELEASE_FILE} --user \"$FTP_USER\":$FTP_PASSWORD ftp://khazaddum.caltech.edu/warpdrive/files/${RELEASE_FILE:0:-4}.${TRAVIS_BUILD_NUMBER}-${TRAVIS_BRANCH}.jar
